import Mathlib

/-!
# Multiquadratic fields and genus theory: target signatures

The narrative roadmap (the layer-by-layer build plan Layers 0–3, the worked examples, and
the references) is in `README.md`. Mathlib has quadratic fields, Kummer theory, quadratic
reciprocity, and the class group, but nothing on multiquadratic extensions
`ℚ(√d₁, …, √dₙ)` or the genus theory they encode; we build that here in `TauCeti/`.

This file holds the **Layer 0** targets (the degree and Galois group of a multiquadratic
field under square-class independence), a non-vacuity worked example, and the **Layer 1**
prime-splitting law. They elaborate against the pinned Mathlib and are stated with `sorry`
(allowed in this human-owned roadmap library). As later layers make their types expressible
in `TauCeti/`, add their milestones here with `sorry`: the 2-elementary quotient `Cl/Cl²`
(Layer 2), and the genus field with the 2-rank theorem (Layer 3).

The Layer-0 square-class machinery is migrated from
[kim-em/erdos-unit-distance](https://github.com/kim-em/erdos-unit-distance); credit it in
the ported `TauCeti/` files.
-/

namespace TauCetiRoadmap.Multiquadratic

universe u v

/-- **Non-vacuity worked example.** The smallest nontrivial multiquadratic degree:
`[ℚ(√2, √3) : ℚ] = 4`. -/
example :
    Module.finrank ℚ
      (IntermediateField.adjoin ℚ {Real.sqrt 2, Real.sqrt 3} : IntermediateField ℚ ℝ) = 4 :=
  sorry

variable {K : Type u} {L : Type v} [Field K] [Field L] [Algebra K L]

/-- **Layer 0, multiquadratic degree.** If no nonempty subset product of the radicands
`d i` is a square in `K` (square-class / `ZMod 2`-linear independence of their classes in
`Kˣ ⧸ (Kˣ)²`), then the field generated over `K` by their square roots `r i` has degree
`2 ^ |ι|`. The rational and prime-indexed versions are corollaries; the field-generic
statement is the theorem. -/
example {ι : Type*} [Fintype ι] [CharZero K] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    Module.finrank K (IntermediateField.adjoin K (Set.range r)) = 2 ^ Fintype.card ι :=
  sorry

/-- **Layer 0, the extension is Galois.** The easy half of the Galois milestone, stated
separately so it can be discharged first: in characteristic zero a field generated by
square roots of base elements is normal (the conjugate of `r i` is `±r i`) and separable,
hence Galois. No square-class independence is needed for this half. -/
example {ι : Type*} [Fintype ι] [CharZero K] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i)) :
    IsGalois K ↥(IntermediateField.adjoin K (Set.range r)) :=
  sorry

/-- **Layer 0, the Galois group is elementary abelian of exponent 2.** Under the same
square-class independence, `K(√d₁, …, √dₙ)/K` is Galois with group `(ℤ/2)ⁿ`, generated by
the sign changes `√dⱼ ↦ ±√dⱼ`. (⚠ `IsGalois` and the exponent-2 facts are the easy half;
this explicit isomorphism is the harder, later target.) -/
example {ι : Type*} [Fintype ι] [CharZero K] (d : ι → K) (r : ι → L)
    (hr : ∀ i, r i ^ 2 = algebraMap K L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, d i)) :
    (↥(IntermediateField.adjoin K (Set.range r)) ≃ₐ[K]
        ↥(IntermediateField.adjoin K (Set.range r))) ≃* Multiplicative (ι → ZMod 2) :=
  sorry

/-- **Layer 1, the prime-splitting law.** Let `K = ℚ(√d₁, …, √dₙ)` be a multiquadratic
number field (`r i` a square root of the integer `d i`, the `r i` generating `K` over `ℚ`).
For an odd prime `p` dividing none of the `d i`, `p` splits completely in `K` (there are
`[K:ℚ]` primes of `𝓞 K` above `p`) if and only if every `d i` is a quadratic residue mod
`p`, i.e. `legendreSym p (d i) = 1` for all `i`. More precisely the Frobenius at `p`, viewed
in `Gal(K/ℚ) ≅ (ℤ/2)ⁿ`, is the sign vector `(legendreSym p (d i))ᵢ`; this is the
splitting-completely specialization. -/
example (K : Type*) [Field K] [NumberField K] {ι : Type*} [Fintype ι]
    (d : ι → ℤ) (r : ι → K) (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i))
    (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
    (p : ℕ) [Fact p.Prime] (hodd : p ≠ 2) (hcop : ∀ i, ¬ (p : ℤ) ∣ d i) :
    Nat.card (Ideal.primesOver (Ideal.span {(p : ℤ)}) (NumberField.RingOfIntegers K))
        = Module.finrank ℚ K ↔
      ∀ i, legendreSym p (d i) = 1 :=
  sorry

end TauCetiRoadmap.Multiquadratic
